# io
input: ./data/input/100people.mp4
output_path: ./data/output/out_100people.mp4

gpu_id: 1

# posenet
pose_model_name: pose_hrnet
pose_model_weight: ./weights/pose_hrnet_w32_256x192.pth
write_box: True
img_size:
  - 256
  - 256